[package]
name = "Game-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "0.2", features = ["macros", "sync", "rt-threaded"] }
warp = "0.2"
futures = { version = "0.3", default-features = false }