name: website

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 17.3
      uses: actions/setup-node@v1
      with:
        node-version: 17.3

    - name: Install
      run: cd website && npm install && npm run theme
      
    - name: WebAssembly
      run: cd website && npm run wasm
        
    - name: Build
      run: cd website && npm run build
